# Generated by Django 2.2.6 on 2019-10-26 06:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 6, 33, 36, 633463, tzinfo=utc)),
        ),
    ]
