# Generated by Django 2.2.6 on 2019-10-26 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 6, 37, 16, 269164, tzinfo=utc)),
        ),
    ]
