# Generated by Django 2.2.6 on 2019-10-26 06:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20191026_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 6, 41, 6, 632985, tzinfo=utc)),
        ),
    ]
